export const NFTs = [
  {
    Id: 1,
    Badge: 'Total Payout: $82,571',
    ImageUrl: '/images/club/feudal_war.png',
    Edition: 17,
    Stock: 132,
    Title: 'FEUDAL WAR',
    Price: '10 ETH',
    Avatar: '/images/avatar/newk3d.png',
    Author: 'Holystargazer',
    Likes: 912,
  },
  {
    Id: 2,
    Badge: 'Total Payout: $77,376',
    ImageUrl: '/images/club/splinterlands.png',
    Edition: 11,
    Stock: 110,
    Title: 'SPLINTER LANDS',
    Price: '10 ETH',
    Avatar: '/images/club/531363.png',
    Author: 'osman76',
    Likes: 771,
  },
  {
    Id: 3,
    Badge: 'Total Payout: $32,231',
    ImageUrl: '/images/club/crypto_ball.png',
    Edition: 13,
    Stock: 96,
    Title: 'CRYPTO BALL',
    Price: '8 ETH',
    Avatar: '/images/club/woman-6193184__480.jpg',
    Author: 'rocketman1',
    Likes: 343,
  },
  {
    Id: 4,
    Badge: 'Total Payout: $8,091',
    ImageUrl: '/images/club/ember.jpg',
    Edition: 3,
    Stock: 65,
    Title: 'EMBER SWORD',
    Price: '6 ETH',
    Avatar: '/images/club/woman-7343219__480.jpg',
    Author: 'therhino3',
    Likes: 767,
  },
  {
    Id: 5,
    Badge: 'Total Payout: $2,112',
    ImageUrl: '/images/club/CryptoDragons.png',
    Edition: 6,
    Stock: 34,
    Title: 'CRYPTO DRAGONS',
    Price: '5 ETH',
    Avatar: '/images/club/hat-1417247__480.jpg',
    Author: 'Donelladan',
    Likes: 892,
  },
  {
    Id: 6,
    Badge: 'Total Payout: $1,891',
    ImageUrl: '/images/club/ninokuni.jpg',
    Edition: 5,
    Stock: 22,
    Title: 'NINO KUNI',
    Price: '5 ETH',
    Avatar: '/images/club/149394.png',
    Author: 'DerStaufer',
    Likes: 329,
  },
];
